### ISSUE TITLE
result of wtsexporter -i -b

### ISSUE THREAD

**Issue by beckietech** [KnugiHK/Whatsapp-Chat-Exporter#2]
Dear KnugiHK, I also tested with iPhone backup from README, and it turned out working fine, again, great project it is! I also noticed there's Media folder in Message folder, and I wonder what's the logic of (0  b  d) folders in (************@s.whatsapp.net) folder?  
also I noticed TODO 2. Reply in iPhone, may I know more detail description of this feature?

**Comment by KnugiHK** [comment]
The logic of folder naming inside @s.whatsap.net is created by WhatsApp. As far as I know, every media will have a UUID as their filename. And the app will take the first two characters of the file name as their parent folders. It is probably about indexing.

In WhatsApp, there is a function for you to reply to a specific message. By using that function, both party in the conversation will know which message you are replying to and when you click that reply, you will be navigated to that message. Reply in iPhone is exactly the same thing. And the reply feature is already present in the Android version of this project.

**Comment by KnugiHK** [comment]
And also, many metadata are not present in iPhone version extraction due to the messy (at least I consider it as messy) data structure of the iPhone WhatsApp database. I am not sure if I can learn their data structure in a short period, so I didn't put that into the TODO list. If anyone has any idea about the data structure in the iPhone database, feel free to contribute.

**Comment by beckietech** [comment]
Dear KnugiHK, thank you for your sharing! and I'm also trying to figure the "messy" database about iPhone(chatStorage.sqlite) and Android(msgstore.db), It will be very helpful to share the ideas! Thanks!
