### ISSUE TITLE
Possible to transfer the IOS Backup to Android? (extracted WhatsApp Files already)

### ISSUE THREAD

**Issue by Dastano** [KnugiHK/WhatsApp-Chat-Exporter#62]
Hey there!

I keep searching the whole day to transfer my IOS WhatsApp Backup to Android, I was able to extract my WhatsApp Files fine.

Just curious, if I somehow can "pack" them, to make Android use it?

**Comment by KnugiHK** [comment]
Theoretically yes. You can. But in practice, there are a lot to do to adopt the schema differeces between iOS and Android.

**Comment by Dastano** [comment]
Since Android Encrypts it? I'm just trying to find a way, I am fine with packing stuff etc. and move it to Gdrive or so.

Would you mind, putting a list or so? If you know how? 

Because I refuse to use any of this Chinese bloatware just to copy my WhatsApp messages.

**Comment by KnugiHK** [comment]
Not because of encryption. The databases of iOS and Android use a totally different schema to store their message, which is also why this project separates the processing of both platforms into multiple script files, although I am considering merging them.

Before doing it ourselves, have you tried https://faq.whatsapp.com/1295296267926284/?

PS. It is always good to refrain from using any Chinese bloatware.
